# Question 1

In [3]:
import numpy
def arrays(arr):
    return(numpy.array(arr[::-1], float))
arr=list(map(int,input().split()))
arrays(arr)

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

# Question 2

In [4]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 3

In [5]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2 
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Question 4

In [6]:
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4 
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Question 5

In [7]:
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Question 6

In [8]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Question 7

In [9]:
import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Question 8

In [10]:
import numpy
numpy.set_printoptions(sign=' ')
a = numpy.array(input().split(),float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Question 9

In [11]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24


# Question 10

In [12]:
print(np.max(np.min(np.array([input().split() for _ in range(int(input().split()[0]))],int),axis=1)))

4 2
2 5
3 7
1 3
4 0
3


# Question 11

In [13]:
import numpy as np
n, m = map(int, input().split())
k = np.array([input().split() for _ in range(n)],dtype = int)
np.set_printoptions(legacy='1.13')
print(np.mean(k,axis=1), np.var(k,axis=0), np.std(k), sep='\n')

2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Question 12

In [14]:
import numpy
n=int(input())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
m = numpy.dot(a,b)
print (m)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Question 13

In [15]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


# Question 14

In [16]:
print(__import__('numpy').polyval(list(map(float,input().split())),float(input())))

1.1 2 3
0
3.0


# Question 15

In [17]:
import numpy
print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) for _ in range(int(input()))])),2))

2
1.1 1.1
1.1 1.1
0.0
